function createOrder_(context,input){
  var productId=cleanString_(input.productId,100); var idem=cleanString_(input.idempotencyKey,120);
  assert_(idem.length>=12,'IDEMPOTENCY_REQUIRED','Esta operación requiere una clave de idempotencia.');
  var prior=findRecord_('IdempotencyKeys','key',context.user.id+':createOrder:'+idem); if(prior){var existing=findRecord_('Orders','id',prior.data.resourceId);if(existing)return sanitizeOrder_(existing.data);}
  var product=findRecord_('Products','id',productId); if(!product||product.data.status!=='PUBLISHED')throw apiError_('PRODUCT_NOT_FOUND','El producto no está disponible.',404);
  if(product.data.sellerId===context.user.id)throw apiError_('OWN_PRODUCT','No puedes comprar tu propio producto.',400);
  var commission=calculateCommission_(Number(product.data.price),product.data.sellerId,input.referralCode); var now=nowIso_(); var order={id:newId_('ord'),buyerId:context.user.id,sellerId:product.data.sellerId,subtotal:Number(product.data.price),platformFee:commission.platformAmount,sellerNet:commission.sellerAmount,currency:product.data.currency,network:'',status:'AWAITING_PAYMENT',idempotencyKey:idem,createdAt:now,updatedAt:now,schemaVersion:1};
  var lock=LockService.getScriptLock();lock.waitLock(30000);try{insertRecord_('Orders',order);insertRecord_('OrderItems',{id:newId_('itm'),orderId:order.id,productId:product.data.id,titleSnapshot:product.data.title,unitPrice:Number(product.data.price),quantity:1,currency:product.data.currency,createdAt:now,schemaVersion:1});insertRecord_('Commissions',{id:newId_('com'),orderId:order.id,sellerId:product.data.sellerId,ruleId:commission.ruleId,grossAmount:commission.grossAmount,platformAmount:commission.platformAmount,sellerAmount:commission.sellerAmount,referralAmount:commission.referralAmount,currency:product.data.currency,status:'PENDING',createdAt:now,schemaVersion:1});insertRecord_('IdempotencyKeys',{key:context.user.id+':createOrder:'+idem,userId:context.user.id,action:'createOrder',resourceId:order.id,responseHash:'',createdAt:now,expiresAt:new Date(Date.now()+86400000).toISOString(),schemaVersion:1});}finally{lock.releaseLock();}
  return sanitizeOrder_(order);
}
function getOrders_(context){return listRecords_('Orders').filter(function(o){return o.buyerId===context.user.id||o.sellerId===context.user.id;}).map(sanitizeOrder_);}
function sanitizeOrder_(o){return{id:o.id,subtotal:Number(o.subtotal),platformFee:Number(o.platformFee),sellerNet:Number(o.sellerNet),currency:o.currency,network:o.network,status:o.status,createdAt:o.createdAt,updatedAt:o.updatedAt};}
function grantOrderAccess_(order){var items=listRecords_('OrderItems').filter(function(i){return i.orderId===order.id;});var existing={};listRecords_('AccessGrants').forEach(function(grant){existing[grant.orderId+':'+grant.productId+':'+grant.userId]=true;});items.forEach(function(item){var key=order.id+':'+item.productId+':'+order.buyerId;if(!existing[key]){insertRecord_('AccessGrants',{id:newId_('acc'),userId:order.buyerId,productId:item.productId,orderId:order.id,grantedAt:nowIso_(),expiresAt:'',status:'ACTIVE',schemaVersion:1});existing[key]=true;}});}
function assertContentAccess_(context,productId){var allowed=listRecords_('AccessGrants').some(function(g){return g.userId===context.user.id&&g.productId===productId&&g.status==='ACTIVE'&&(!g.expiresAt||new Date(g.expiresAt)>new Date());});if(!allowed)throw apiError_('ACCESS_DENIED','No tienes acceso activo a este contenido.',403);return true;}
