/**
 * PROJECT GALAXY — SINGLE-FILE GOOGLE APPS SCRIPT BACKEND
 * Generated by: npm run build:apps-script
 * Deploy this file as Code.gs. Do not upload backend-src/*.js to Apps Script.
 * Source modules are ordered below and remain separated by MODULE headers.
 */

// =============================================================================
// MODULE: Config
// =============================================================================

var APP_CONFIG = Object.freeze({
  APP_NAME: 'PROJECT GALAXY',
  APP_VERSION: '0.1.0',
  DATABASE_SCHEMA_VERSION: '1',
  SESSION_DURATION_SECONDS: 604800,
  PASSWORD_HASH_ROUNDS: 5000,
  PAYMENT_TIMEOUT_MINUTES: 30,
  DEFAULT_COMMISSION_RATE: 0.10,
  PAYMENT_STATES: ['CREATED','PENDING','DETECTING','CONFIRMING','CONFIRMED','FAILED','EXPIRED','REFUNDED','CANCELLED'],
  ROLES: ['USER','CREATOR','SELLER','MODERATOR','ADMIN']
});

var SHEET_SCHEMAS = {
  Users: ['id','name','username','email','passwordHash','passwordSalt','avatar','createdAt','updatedAt','status','role','level','lastLogin','emailVerifiedAt','schemaVersion'],
  Profiles: ['id','userId','cover','bio','xp','followersCount','followingCount','privacyJson','createdAt','updatedAt','schemaVersion'],
  Sessions: ['id','userId','tokenHash','createdAt','expiresAt','revokedAt','lastSeenAt','userAgentHash','schemaVersion'],
  Products: ['id','sellerId','title','description','mediaJson','price','currency','categoryId','stock','status','rating','reviewCount','createdAt','updatedAt','schemaVersion'],
  Orders: ['id','buyerId','sellerId','subtotal','platformFee','sellerNet','currency','network','status','idempotencyKey','createdAt','updatedAt','schemaVersion'],
  OrderItems: ['id','orderId','productId','titleSnapshot','unitPrice','quantity','currency','createdAt','schemaVersion'],
  Payments: ['id','orderId','provider','providerPaymentId','network','tokenContract','destinationAddress','expectedAmount','currency','transactionHash','confirmations','status','expiresAt','confirmedAt','idempotencyKey','createdAt','updatedAt','schemaVersion'],
  Transactions: ['id','userId','type','referenceType','referenceId','amount','currency','network','transactionHash','status','createdAt','schemaVersion'],
  Wallets: ['id','userId','availableBalance','pendingBalance','totalEarned','totalSpent','currency','updatedAt','schemaVersion'],
  Commissions: ['id','orderId','sellerId','ruleId','grossAmount','platformAmount','sellerAmount','referralAmount','currency','status','createdAt','schemaVersion'],
  Withdrawals: ['id','userId','network','address','amount','fee','netAmount','currency','transactionHash','status','createdAt','updatedAt','schemaVersion'],
  Streams: ['id','hostId','title','description','thumbnail','categoryId','status','startedAt','endedAt','viewerCount','createdAt','schemaVersion'],
  Meetings: ['id','hostId','roomCode','roomCodeHash','passwordHash','title','waitingRoom','locked','permissionsJson','status','startsAt','endedAt','createdAt','updatedAt','schemaVersion'],
  MeetingParticipants: ['id','meetingId','userId','role','status','joinedAt','leftAt','permissionsJson','schemaVersion'],
  MeetingInvitations: ['id','meetingId','inviterId','inviteeId','status','createdAt','respondedAt','schemaVersion'],
  MeetingMessages: ['id','meetingId','senderId','body','replyToId','createdAt','editedAt','deletedAt','schemaVersion'],
  MeetingMessageReactions: ['id','meetingId','messageId','userId','emoji','active','createdAt','updatedAt','schemaVersion'],
  Messages: ['id','conversationId','senderId','type','body','attachmentUrl','createdAt','deletedAt','schemaVersion'],
  Notifications: ['id','userId','type','title','body','resourceType','resourceId','readAt','createdAt','schemaVersion'],
  Posts: ['id','authorId','type','body','mediaJson','visibility','premiumProductId','status','createdAt','updatedAt','schemaVersion'],
  Comments: ['id','postId','authorId','parentId','body','status','createdAt','updatedAt','schemaVersion'],
  Likes: ['id','userId','resourceType','resourceId','createdAt','schemaVersion'],
  Reviews: ['id','productId','userId','orderId','rating','body','status','createdAt','updatedAt','schemaVersion'],
  Categories: ['id','name','slug','type','status','createdAt','schemaVersion'],
  Subscriptions: ['id','userId','productId','orderId','period','status','startsAt','expiresAt','createdAt','updatedAt','schemaVersion'],
  AccessGrants: ['id','userId','productId','orderId','grantedAt','expiresAt','status','schemaVersion'],
  SecurityLogs: ['id','userId','event','severity','resourceType','resourceId','ipHash','metadataJson','createdAt','schemaVersion'],
  Settings: ['key','value','type','isSecret','updatedBy','updatedAt','schemaVersion'],
  IdempotencyKeys: ['key','userId','action','resourceId','responseHash','createdAt','expiresAt','schemaVersion'],
  WebhookEvents: ['id','provider','eventId','signatureHash','status','receivedAt','processedAt','schemaVersion']
};

function getPublicConfig_() {
  var settings=getSettingsMap_();function setting(key,fallback){return Object.prototype.hasOwnProperty.call(settings,key)?settings[key]:fallback;}function booleanSetting(key,fallback){return String(setting(key,fallback)).toLowerCase()==='true';}
  return {
    appName: setting('APP_NAME', APP_CONFIG.APP_NAME),
    appVersion: APP_CONFIG.APP_VERSION,
    registrationEnabled: booleanSetting('REGISTRATION_ENABLED', true),
    marketplaceEnabled: booleanSetting('MARKETPLACE_ENABLED', true),
    meetingsEnabled: booleanSetting('MEETINGS_ENABLED', true),
    streamingEnabled: booleanSetting('STREAMING_ENABLED', false),
    maintenanceMode: booleanSetting('MAINTENANCE_MODE', false),
    networks: getEnabledNetworks_()
  };
}

// =============================================================================
// MODULE: Utils
// =============================================================================

var REQUEST_CONTEXT_ = null;

function beginRequest_() { REQUEST_CONTEXT_ = { sheetReads:0, sheetWrites:0, cacheHits:0, recordCache:{}, listCache:{}, responseBytes:0 }; }
function metric_(key, amount) { if (REQUEST_CONTEXT_) REQUEST_CONTEXT_[key] = Number(REQUEST_CONTEXT_[key] || 0) + Number(amount || 1); }
function invalidateRequestData_(sheetName) { if (!REQUEST_CONTEXT_) return; delete REQUEST_CONTEXT_.listCache[sheetName]; REQUEST_CONTEXT_.recordCache = {}; }

function getDatabase_() {
  var properties = PropertiesService.getScriptProperties();
  var id = properties.getProperty('SPREADSHEET_ID');
  var spreadsheet = id ? SpreadsheetApp.openById(id) : SpreadsheetApp.getActiveSpreadsheet();
  if (!spreadsheet) spreadsheet = SpreadsheetApp.create(APP_CONFIG.APP_NAME + ' - Database');
  if (!id) properties.setProperty('SPREADSHEET_ID', spreadsheet.getId());
  return spreadsheet;
}

function getSchemaFingerprint_() { return sha256_(JSON.stringify(SHEET_SCHEMAS)); }

function ensureSecurityProperties_() {
  var properties = PropertiesService.getScriptProperties();
  if (!properties.getProperty('PASSWORD_PEPPER')) properties.setProperty('PASSWORD_PEPPER', randomToken_() + randomToken_());
  if (!properties.getProperty('MEETING_TOKEN_SECRET')) properties.setProperty('MEETING_TOKEN_SECRET', randomToken_() + randomToken_());
}

function ensureApplicationReady_() {
  var properties = PropertiesService.getScriptProperties();
  if (!properties.getProperty('PASSWORD_PEPPER') || !properties.getProperty('MEETING_TOKEN_SECRET') || properties.getProperty('DATABASE_SCHEMA_FINGERPRINT') !== getSchemaFingerprint_()) initializeDatabase();
}

function initializeDatabase() {
  var lock = LockService.getScriptLock(); lock.waitLock(30000);
  try {
    var spreadsheet = getDatabase_(); var report = { created: [], migrated: [], unchanged: [] };
    Object.keys(SHEET_SCHEMAS).forEach(function(name) {
      var schema = SHEET_SCHEMAS[name]; var sheet = spreadsheet.getSheetByName(name);
      if (!sheet) { sheet = spreadsheet.insertSheet(name); sheet.getRange(1, 1, 1, schema.length).setValues([schema]); sheet.setFrozenRows(1); styleHeader_(sheet, schema.length); report.created.push(name); return; }
      var lastColumn = Math.max(sheet.getLastColumn(), 1); var existing = sheet.getLastRow() ? sheet.getRange(1, 1, 1, lastColumn).getValues()[0].filter(String) : [];
      if (!existing.length) { sheet.getRange(1, 1, 1, schema.length).setValues([schema]); styleHeader_(sheet, schema.length); report.migrated.push(name); return; }
      var missing = schema.filter(function(column) { return existing.indexOf(column) === -1; });
      if (missing.length) { sheet.getRange(1, existing.length + 1, 1, missing.length).setValues([missing]); styleHeader_(sheet, existing.length + missing.length); report.migrated.push(name); } else report.unchanged.push(name);
    });
    ensureSecurityProperties_(); seedSettings_(); bootstrapAdmin_();
    PropertiesService.getScriptProperties().setProperties({
      DATABASE_SCHEMA_VERSION: APP_CONFIG.DATABASE_SCHEMA_VERSION,
      DATABASE_SCHEMA_FINGERPRINT: getSchemaFingerprint_(),
      SPREADSHEET_ID: spreadsheet.getId()
    }, false);
    report.spreadsheetId = spreadsheet.getId();
    return report;
  } finally { lock.releaseLock(); }
}

function styleHeader_(sheet, columns) { sheet.getRange(1, 1, 1, columns).setFontWeight('bold').setBackground('#17121f').setFontColor('#f4efff'); }
function newId_(prefix) { return prefix + '_' + Utilities.getUuid().replace(/-/g, ''); }
function nowIso_() { return new Date().toISOString(); }
function apiError_(code, message, status) { var error = new Error(message); error.code = code; error.publicMessage = message; error.status = status || 400; return error; }
function requireMethod_(actual, expected) { if (actual !== expected) throw apiError_('METHOD_NOT_ALLOWED', 'Método no permitido.', 405); }
function cleanString_(value, max) { return String(value || '').trim().slice(0, max || 500); }
function normalizeEmail_(value) { return cleanString_(value, 254).toLowerCase(); }
function assert_(condition, code, message) { if (!condition) throw apiError_(code, message, 400); }
function randomToken_() { return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, Utilities.getUuid() + ':' + Date.now() + ':' + Math.random())).replace(/=+$/, ''); }
function sha256_(value) { return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, String(value))).replace(/=+$/, ''); }

function getHeaders_(sheet) { if (!sheet || sheet.getLastRow() < 1) return []; metric_('sheetReads'); return sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0]; }
function rowToObject_(headers, row) { var result = {}; headers.forEach(function(key, i) { if (key) result[key] = row[i]; }); return result; }
function objectToRow_(headers, object) { return headers.map(function(key) { return object[key] === undefined ? '' : object[key]; }); }
function findRecord_(sheetName, column, value) {
  var cacheKey=sheetName+':'+column+':'+String(value);if(REQUEST_CONTEXT_&&Object.prototype.hasOwnProperty.call(REQUEST_CONTEXT_.recordCache,cacheKey)){metric_('cacheHits');return REQUEST_CONTEXT_.recordCache[cacheKey];}
  var sheet = getDatabase_().getSheetByName(sheetName); if (!sheet || sheet.getLastRow() < 2) return null;
  var headers = getHeaders_(sheet); var index = headers.indexOf(column); if (index < 0) throw new Error('Missing column: ' + column);
  metric_('sheetReads');
  var match = sheet.getRange(2, index + 1, sheet.getLastRow() - 1, 1).createTextFinder(String(value)).matchEntireCell(true).findNext();
  if (!match){if(REQUEST_CONTEXT_)REQUEST_CONTEXT_.recordCache[cacheKey]=null;return null;}metric_('sheetReads');var result={ rowNumber: match.getRow(), data: rowToObject_(headers, sheet.getRange(match.getRow(), 1, 1, headers.length).getValues()[0]) };if(REQUEST_CONTEXT_)REQUEST_CONTEXT_.recordCache[cacheKey]=result;return result;
}
function insertRecord_(sheetName, object) { var sheet = getDatabase_().getSheetByName(sheetName); if (!sheet) throw new Error('Database not initialized'); var headers = getHeaders_(sheet); sheet.getRange(sheet.getLastRow() + 1, 1, 1, headers.length).setValues([objectToRow_(headers, object)]);metric_('sheetWrites');invalidateRequestData_(sheetName); return object; }
function updateRecord_(sheetName, rowNumber, patch) { var sheet = getDatabase_().getSheetByName(sheetName); var headers = getHeaders_(sheet);metric_('sheetReads'); var row = sheet.getRange(rowNumber, 1, 1, headers.length).getValues()[0]; Object.keys(patch).forEach(function(key) { var i = headers.indexOf(key); if (i >= 0) row[i] = patch[key]; }); sheet.getRange(rowNumber, 1, 1, headers.length).setValues([row]);metric_('sheetWrites');invalidateRequestData_(sheetName); return rowToObject_(headers, row); }
function listRecords_(sheetName) { if(REQUEST_CONTEXT_&&Object.prototype.hasOwnProperty.call(REQUEST_CONTEXT_.listCache,sheetName)){metric_('cacheHits');return REQUEST_CONTEXT_.listCache[sheetName];}var sheet = getDatabase_().getSheetByName(sheetName); if (!sheet || sheet.getLastRow() < 2){if(REQUEST_CONTEXT_)REQUEST_CONTEXT_.listCache[sheetName]=[];return [];} var headers = getHeaders_(sheet);metric_('sheetReads');var records=sheet.getRange(2, 1, sheet.getLastRow() - 1, headers.length).getValues().map(function(row) { return rowToObject_(headers, row); });if(REQUEST_CONTEXT_)REQUEST_CONTEXT_.listCache[sheetName]=records;return records; }
function getSettingsMap_(){var cache=CacheService.getScriptCache();var cached=cache.get('settings:all');if(cached){metric_('cacheHits');try{return JSON.parse(cached);}catch(ignore){}}var map={};listRecords_('Settings').forEach(function(row){if(String(row.isSecret).toLowerCase()!=='true')map[row.key]=row.value;});cache.put('settings:all',JSON.stringify(map),300);return map;}
function getSetting_(key, fallback) { var settings=getSettingsMap_();return Object.prototype.hasOwnProperty.call(settings,key)?settings[key]:fallback; }
function getBooleanSetting_(key, fallback) { return String(getSetting_(key, fallback)).toLowerCase() === 'true'; }
function seedSettings_() { var defaults = { APP_NAME: APP_CONFIG.APP_NAME, REGISTRATION_ENABLED: true, MARKETPLACE_ENABLED: true, MEETINGS_ENABLED: true, STREAMING_ENABLED: false, MAINTENANCE_MODE: false, COMMISSION_RATE: APP_CONFIG.DEFAULT_COMMISSION_RATE, PAYMENT_EXPIRATION_MINUTES: 30, TRC20_ENABLED: false, ERC20_ENABLED: false, MINIMUM_WITHDRAWAL: 10 };var existing={};listRecords_('Settings').forEach(function(row){existing[row.key]=true;});Object.keys(defaults).forEach(function(key) { if (!existing[key]) insertRecord_('Settings',{ key:key,value:String(defaults[key]),type:typeof defaults[key],isSecret:false,updatedBy:'system',updatedAt:nowIso_(),schemaVersion:1 }); });CacheService.getScriptCache().remove('settings:all'); }
function observeRequest_(action, duration, ok) { var metrics=REQUEST_CONTEXT_||{};console.log(JSON.stringify({ type:'api_request',action:action,durationMs:duration,ok:ok,sheetReads:metrics.sheetReads||0,sheetWrites:metrics.sheetWrites||0,cacheHits:metrics.cacheHits||0,responseBytes:metrics.responseBytes||0 })); }

// =============================================================================
// MODULE: Security
// =============================================================================

function logSecurityEvent_(userId,event,severity,resourceType,resourceId,metadata) {
  try { insertRecord_('SecurityLogs',{ id:newId_('sec'),userId:userId||'',event:event,severity:severity,resourceType:resourceType||'',resourceId:resourceId||'',ipHash:'',metadataJson:JSON.stringify(metadata||{}).slice(0,2000),createdAt:nowIso_(),schemaVersion:1 }); } catch (error) { console.error('Security log failure: '+error.message); }
}

function enforceRateLimit_(action, body) {
  var sensitive = ['login','register','createPayment','verifyPayment','joinMeeting','postMeetingMessage','reactToMeetingMessage','inviteToMeeting','postMeetingSignals']; if (sensitive.indexOf(action) < 0) return;
  var subject = sha256_(cleanString_(body.email || body.sessionToken || 'anonymous',300)); var key='rate:'+action+':'+subject; var cache=CacheService.getScriptCache(); var count=Number(cache.get(key)||0)+1;
  var limit=action==='postMeetingSignals'?180:(action==='postMeetingMessage'||action==='reactToMeetingMessage'?60:20);
  if (count>limit) throw apiError_('RATE_LIMITED','Demasiados intentos. Espera un minuto y vuelve a intentarlo.',429);
  cache.put(key,String(count),60);
}

function getHealth_() { var properties=PropertiesService.getScriptProperties();return { status:'operational',version:APP_CONFIG.APP_VERSION,databaseInitialized:properties.getProperty('DATABASE_SCHEMA_FINGERPRINT')===getSchemaFingerprint_(),securityConfigured:!!properties.getProperty('PASSWORD_PEPPER'),meetingTokensConfigured:!!properties.getProperty('MEETING_TOKEN_SECRET'),signalingConfigured:!!properties.getProperty('SIGNALING_URL'),timestamp:nowIso_() }; }

// =============================================================================
// MODULE: Auth
// =============================================================================

function hashPassword_(password, salt) {
  var pepper = PropertiesService.getScriptProperties().getProperty('PASSWORD_PEPPER');
  if (!pepper) { ensureApplicationReady_(); pepper = PropertiesService.getScriptProperties().getProperty('PASSWORD_PEPPER'); }
  if (!pepper) throw apiError_('SECURITY_NOT_CONFIGURED', 'No fue posible inicializar la seguridad de autenticación.', 503);
  var output = String(password) + ':' + salt + ':' + pepper;
  for (var i = 0; i < APP_CONFIG.PASSWORD_HASH_ROUNDS; i++) output = sha256_(output + ':' + i);
  return output;
}

function registerUser_(input) {
  if (!getBooleanSetting_('REGISTRATION_ENABLED', true)) throw apiError_('REGISTRATION_DISABLED', 'El registro está temporalmente desactivado.', 403);
  var name = cleanString_(input.name, 100); var username = cleanString_(input.username, 32).toLowerCase(); var email = normalizeEmail_(input.email); var password = String(input.password || '');
  assert_(name.length >= 2, 'INVALID_NAME', 'Ingresa un nombre válido.');
  assert_(/^[a-z0-9_]{3,32}$/.test(username), 'INVALID_USERNAME', 'El usuario debe tener 3–32 caracteres: letras, números o guion bajo.');
  assert_(/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email), 'INVALID_EMAIL', 'Ingresa un correo válido.');
  assert_(password.length >= 10, 'WEAK_PASSWORD', 'La contraseña debe tener al menos 10 caracteres.');
  if (findRecord_('Users','email',email)) throw apiError_('EMAIL_EXISTS', 'Ya existe una cuenta con este correo.', 409);
  if (findRecord_('Users','username',username)) throw apiError_('USERNAME_EXISTS', 'Ese nombre de usuario ya está ocupado.', 409);
  var salt = randomToken_(); var now = nowIso_();
  var user = { id:newId_('usr'),name:name,username:username,email:email,passwordHash:hashPassword_(password,salt),passwordSalt:salt,avatar:'',createdAt:now,updatedAt:now,status:'ACTIVE',role:'USER',level:1,lastLogin:'',emailVerifiedAt:'',schemaVersion:1 };
  insertRecord_('Users', user); insertRecord_('Profiles',{ id:newId_('pro'),userId:user.id,cover:'',bio:'',xp:0,followersCount:0,followingCount:0,privacyJson:'{}',createdAt:now,updatedAt:now,schemaVersion:1 });
  insertRecord_('Wallets',{ id:newId_('wal'),userId:user.id,availableBalance:0,pendingBalance:0,totalEarned:0,totalSpent:0,currency:'USDT',updatedAt:now,schemaVersion:1 });
  logSecurityEvent_(user.id,'REGISTER','INFO','User',user.id,{});
  return createSession_(user);
}

function loginUser_(input) {
  var email = normalizeEmail_(input.email); var password = String(input.password || '');
  var found = findRecord_('Users','email',email);
  if (!found || !constantTimeEqual_(hashPassword_(password, found ? found.data.passwordSalt : 'invalid-salt'), found ? found.data.passwordHash : sha256_('invalid'))) {
    logSecurityEvent_('', 'LOGIN_FAILED', 'WARNING', 'User', '', { emailHash: sha256_(email) });
    throw apiError_('INVALID_CREDENTIALS', 'El correo o la contraseña no coinciden.', 401);
  }
  if (found.data.status !== 'ACTIVE') throw apiError_('ACCOUNT_UNAVAILABLE', 'La cuenta no está activa.', 403);
  var now = nowIso_(); updateRecord_('Users', found.rowNumber, { lastLogin:now,updatedAt:now });
  logSecurityEvent_(found.data.id,'LOGIN','INFO','User',found.data.id,{});
  return createSession_(found.data);
}

function createSession_(user) {
  var rawToken = randomToken_(); var now = new Date(); var expires = new Date(now.getTime() + APP_CONFIG.SESSION_DURATION_SECONDS * 1000);
  insertRecord_('Sessions',{ id:newId_('ses'),userId:user.id,tokenHash:sha256_(rawToken),createdAt:now.toISOString(),expiresAt:expires.toISOString(),revokedAt:'',lastSeenAt:now.toISOString(),userAgentHash:'',schemaVersion:1 });
  return { token:rawToken,user:sanitizeUser_(user),expiresAt:expires.getTime() };
}

function requireSession_(input) {
  var token = cleanString_(input.sessionToken || input.token, 300);
  if (!token) throw apiError_('AUTH_REQUIRED', 'Inicia sesión para continuar.', 401);
  var found = findRecord_('Sessions','tokenHash',sha256_(token));
  if (!found || found.data.revokedAt || new Date(found.data.expiresAt).getTime() <= Date.now()) throw apiError_('SESSION_INVALID', 'Tu sesión expiró o fue revocada.', 401);
  var user = findRecord_('Users','id',found.data.userId);
  if (!user || user.data.status !== 'ACTIVE') throw apiError_('SESSION_INVALID', 'La cuenta no está disponible.', 401);
  if(!found.data.lastSeenAt||Date.now()-new Date(found.data.lastSeenAt).getTime()>300000)updateRecord_('Sessions', found.rowNumber, { lastSeenAt:nowIso_() });
  return { session:found.data,user:user.data };
}

function logoutUser_(context) { var found = findRecord_('Sessions','id',context.session.id); if (found) updateRecord_('Sessions',found.rowNumber,{ revokedAt:nowIso_() }); logSecurityEvent_(context.user.id,'LOGOUT','INFO','Session',context.session.id,{}); return { loggedOut:true }; }
function sanitizeUser_(user) { return { id:user.id,name:user.name,username:user.username,email:user.email,avatar:user.avatar,role:user.role,level:Number(user.level || 1),status:user.status,createdAt:user.createdAt,emailVerified:!!user.emailVerifiedAt }; }
function requireAdmin_(context) { if (context.user.role !== 'ADMIN') throw apiError_('FORBIDDEN','No tienes permiso para realizar esta acción.',403); return context; }
function constantTimeEqual_(a,b) { a=String(a); b=String(b); var mismatch=a.length^b.length; var length=Math.max(a.length,b.length); for(var i=0;i<length;i++) mismatch|=(a.charCodeAt(i%Math.max(a.length,1))||0)^(b.charCodeAt(i%Math.max(b.length,1))||0); return mismatch===0; }

function bootstrapAdmin_() {
  var email = normalizeEmail_(PropertiesService.getScriptProperties().getProperty('BOOTSTRAP_ADMIN_EMAIL'));
  if (!email || findRecord_('Users','email',email)) return;
  var temporaryPassword = PropertiesService.getScriptProperties().getProperty('BOOTSTRAP_ADMIN_PASSWORD');
  if (!temporaryPassword || temporaryPassword.length < 14) { console.warn('Admin bootstrap skipped: set a strong BOOTSTRAP_ADMIN_PASSWORD temporarily.'); return; }
  var salt=randomToken_(), now=nowIso_();
  insertRecord_('Users',{ id:newId_('usr'),name:'Platform Administrator',username:'admin_'+Utilities.getUuid().slice(0,6),email:email,passwordHash:hashPassword_(temporaryPassword,salt),passwordSalt:salt,avatar:'',createdAt:now,updatedAt:now,status:'ACTIVE',role:'ADMIN',level:1,lastLogin:'',emailVerifiedAt:now,schemaVersion:1 });
  PropertiesService.getScriptProperties().deleteProperty('BOOTSTRAP_ADMIN_PASSWORD');
}

// =============================================================================
// MODULE: Users
// =============================================================================

function getUserProfile_(context, requestedUserId) {
  var userId = requestedUserId || context.user.id;
  if (userId !== context.user.id && ['ADMIN','MODERATOR'].indexOf(context.user.role) < 0) throw apiError_('FORBIDDEN','No puedes acceder a este perfil privado.',403);
  var profile = findRecord_('Profiles','userId',userId);
  return { user:sanitizeUser_(findRecord_('Users','id',userId).data), profile:profile ? profile.data : null };
}

function updateOwnProfile_(context, input) {
  var found = findRecord_('Profiles','userId',context.user.id); if (!found) throw apiError_('NOT_FOUND','No encontramos el perfil.',404);
  return updateRecord_('Profiles',found.rowNumber,{ bio:cleanString_(input.bio,500),cover:cleanString_(input.cover,1000),privacyJson:JSON.stringify(input.privacy || {}),updatedAt:nowIso_() });
}

// =============================================================================
// MODULE: Marketplace
// =============================================================================

function listProducts_(input) {
  if (!getBooleanSetting_('MARKETPLACE_ENABLED',true)) throw apiError_('MARKETPLACE_DISABLED','El marketplace está temporalmente desactivado.',503);
  var query=cleanString_(input.query,100).toLowerCase(); var category=cleanString_(input.category,100);
  return listRecords_('Products').filter(function(p){ return p.status==='PUBLISHED' && (!query || (p.title+' '+p.description).toLowerCase().indexOf(query)>=0) && (!category || p.categoryId===category); }).slice(0,100).map(sanitizeProduct_);
}
function getProduct_(id) { var found=findRecord_('Products','id',cleanString_(id,100)); if(!found || found.data.status!=='PUBLISHED') throw apiError_('PRODUCT_NOT_FOUND','No encontramos este producto.',404); return sanitizeProduct_(found.data); }
function sanitizeProduct_(p) { return { id:p.id,sellerId:p.sellerId,title:p.title,description:p.description,media:parseJsonSafe_(p.mediaJson,[]),price:Number(p.price),currency:p.currency,categoryId:p.categoryId,stock:p.stock===''?null:Number(p.stock),rating:Number(p.rating||0),reviewCount:Number(p.reviewCount||0),createdAt:p.createdAt }; }
function parseJsonSafe_(value,fallback){ try{return JSON.parse(value);}catch(ignore){return fallback;} }

function createReview_(context,input){
  var productId=cleanString_(input.productId,100); var rating=Number(input.rating); assert_(rating>=1&&rating<=5,'INVALID_RATING','La calificación debe estar entre 1 y 5.');
  var ordersById={};listRecords_('Orders').forEach(function(order){ordersById[order.id]=order;});var qualifying=listRecords_('OrderItems').filter(function(item){var order=ordersById[item.orderId];return item.productId===productId&&order&&order.buyerId===context.user.id&&order.status==='COMPLETED';});
  if(!qualifying.length) throw apiError_('PURCHASE_REQUIRED','Solo los compradores verificados pueden reseñar este producto.',403);
  if(findRecord_('Reviews','orderId',qualifying[0].orderId)) throw apiError_('REVIEW_EXISTS','Esta compra ya tiene una reseña.',409);
  return insertRecord_('Reviews',{id:newId_('rev'),productId:productId,userId:context.user.id,orderId:qualifying[0].orderId,rating:rating,body:cleanString_(input.body,2000),status:'PUBLISHED',createdAt:nowIso_(),updatedAt:nowIso_(),schemaVersion:1});
}

// =============================================================================
// MODULE: Commissions
// =============================================================================

function calculateCommission_(gross,sellerId,referralCode){
  var rate=Number(getSetting_('COMMISSION_RATE',APP_CONFIG.DEFAULT_COMMISSION_RATE));
  if(!isFinite(rate)||rate<0||rate>1)throw apiError_('INVALID_COMMISSION_CONFIG','La configuración de comisiones no es válida.',503);
  var referralRate=0; var platform=roundMoney_(gross*rate); var referral=roundMoney_(gross*referralRate); return{ruleId:'default-v1',grossAmount:roundMoney_(gross),platformAmount:platform,sellerAmount:roundMoney_(gross-platform-referral),referralAmount:referral};
}
function roundMoney_(value){return Math.round((Number(value)+Number.EPSILON)*1000000)/1000000;}

// =============================================================================
// MODULE: Orders
// =============================================================================

function createOrder_(context,input){
  var productId=cleanString_(input.productId,100); var idem=cleanString_(input.idempotencyKey,120);
  assert_(idem.length>=12,'IDEMPOTENCY_REQUIRED','Esta operación requiere una clave de idempotencia.');
  var prior=findRecord_('IdempotencyKeys','key',context.user.id+':createOrder:'+idem); if(prior){var existing=findRecord_('Orders','id',prior.data.resourceId);if(existing)return sanitizeOrder_(existing.data);}
  var product=findRecord_('Products','id',productId); if(!product||product.data.status!=='PUBLISHED')throw apiError_('PRODUCT_NOT_FOUND','El producto no está disponible.',404);
  if(product.data.sellerId===context.user.id)throw apiError_('OWN_PRODUCT','No puedes comprar tu propio producto.',400);
  var commission=calculateCommission_(Number(product.data.price),product.data.sellerId,input.referralCode); var now=nowIso_(); var order={id:newId_('ord'),buyerId:context.user.id,sellerId:product.data.sellerId,subtotal:Number(product.data.price),platformFee:commission.platformAmount,sellerNet:commission.sellerAmount,currency:product.data.currency,network:'',status:'AWAITING_PAYMENT',idempotencyKey:idem,createdAt:now,updatedAt:now,schemaVersion:1};
  var lock=LockService.getScriptLock();lock.waitLock(30000);try{insertRecord_('Orders',order);insertRecord_('OrderItems',{id:newId_('itm'),orderId:order.id,productId:product.data.id,titleSnapshot:product.data.title,unitPrice:Number(product.data.price),quantity:1,currency:product.data.currency,createdAt:now,schemaVersion:1});insertRecord_('Commissions',{id:newId_('com'),orderId:order.id,sellerId:product.data.sellerId,ruleId:commission.ruleId,grossAmount:commission.grossAmount,platformAmount:commission.platformAmount,sellerAmount:commission.sellerAmount,referralAmount:commission.referralAmount,currency:product.data.currency,status:'PENDING',createdAt:now,schemaVersion:1});insertRecord_('IdempotencyKeys',{key:context.user.id+':createOrder:'+idem,userId:context.user.id,action:'createOrder',resourceId:order.id,responseHash:'',createdAt:now,expiresAt:new Date(Date.now()+86400000).toISOString(),schemaVersion:1});}finally{lock.releaseLock();}
  return sanitizeOrder_(order);
}
function getOrders_(context){return listRecords_('Orders').filter(function(o){return o.buyerId===context.user.id||o.sellerId===context.user.id;}).map(sanitizeOrder_);}
function sanitizeOrder_(o){return{id:o.id,subtotal:Number(o.subtotal),platformFee:Number(o.platformFee),sellerNet:Number(o.sellerNet),currency:o.currency,network:o.network,status:o.status,createdAt:o.createdAt,updatedAt:o.updatedAt};}
function grantOrderAccess_(order){var items=listRecords_('OrderItems').filter(function(i){return i.orderId===order.id;});var existing={};listRecords_('AccessGrants').forEach(function(grant){existing[grant.orderId+':'+grant.productId+':'+grant.userId]=true;});items.forEach(function(item){var key=order.id+':'+item.productId+':'+order.buyerId;if(!existing[key]){insertRecord_('AccessGrants',{id:newId_('acc'),userId:order.buyerId,productId:item.productId,orderId:order.id,grantedAt:nowIso_(),expiresAt:'',status:'ACTIVE',schemaVersion:1});existing[key]=true;}});}
function assertContentAccess_(context,productId){var allowed=listRecords_('AccessGrants').some(function(g){return g.userId===context.user.id&&g.productId===productId&&g.status==='ACTIVE'&&(!g.expiresAt||new Date(g.expiresAt)>new Date());});if(!allowed)throw apiError_('ACCESS_DENIED','No tienes acceso activo a este contenido.',403);return true;}

// =============================================================================
// MODULE: Crypto
// =============================================================================

function getEnabledNetworks_(){
  var settings=getSettingsMap_();return ['TRC20','ERC20'].filter(function(network){return String(settings[network+'_ENABLED']||'false').toLowerCase()==='true';}).map(function(network){return{network:network,token:'USDT',contractConfigured:!!PropertiesService.getScriptProperties().getProperty('USDT_'+network+'_CONTRACT')};});
}

function getCryptoPaymentProvider_(network){
  var allowed=getEnabledNetworks_().some(function(n){return n.network===network&&n.contractConfigured;});
  if(!allowed)throw apiError_('NETWORK_NOT_CONFIGURED','Esta red no tiene un proveedor y contrato verificados configurados.',503);
  var providerName=PropertiesService.getScriptProperties().getProperty('PAYMENT_PROVIDER_'+network);
  if(!providerName)throw apiError_('PAYMENT_PROVIDER_NOT_CONFIGURED','Configura un proveedor de pagos compatible antes de aceptar fondos.',503);
  // Register audited provider adapters here. Unknown names must fail closed.
  throw apiError_('PAYMENT_PROVIDER_NOT_IMPLEMENTED','El adaptador configurado todavía no está instalado.',503);
}

function validateNetworkAddress_(network,address){
  address=cleanString_(address,150);
  if(network==='ERC20'&&!/^0x[a-fA-F0-9]{40}$/.test(address))throw apiError_('INVALID_ADDRESS','La dirección ERC20 no es válida.',400);
  if(network==='TRC20'&&!/^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(address))throw apiError_('INVALID_ADDRESS','La dirección TRC20 no es válida.',400);
  return address;
}

function validateVerifiedTransfer_(payment,verification){
  var configuredContract=PropertiesService.getScriptProperties().getProperty('USDT_'+payment.network+'_CONTRACT');
  assert_(verification.transactionHash,'TRANSFER_INVALID','Falta el hash de la transacción.');
  assert_(verification.network===payment.network,'TRANSFER_NETWORK_MISMATCH','La red no coincide.');
  assert_(String(verification.tokenContract).toLowerCase()===String(configuredContract).toLowerCase(),'TOKEN_CONTRACT_MISMATCH','El contrato del token no coincide.');
  assert_(String(verification.destinationAddress).toLowerCase()===String(payment.destinationAddress).toLowerCase(),'DESTINATION_MISMATCH','La dirección de destino no coincide.');
  assert_(Number(verification.amount)>=Number(payment.expectedAmount),'AMOUNT_MISMATCH','El importe recibido es insuficiente.');
  assert_(Number(verification.confirmations)>=Number(getSetting_('MIN_CONFIRMATIONS_'+payment.network,12)),'CONFIRMATIONS_PENDING','La transacción aún no tiene suficientes confirmaciones.');
  if(findRecord_('Payments','transactionHash',verification.transactionHash))throw apiError_('TRANSACTION_REUSED','Esta transacción ya fue utilizada.',409);
  return true;
}

// =============================================================================
// MODULE: Payments
// =============================================================================

function createPayment_(context,input){
  var order=findRecord_('Orders','id',cleanString_(input.orderId,100)); if(!order||order.data.buyerId!==context.user.id)throw apiError_('ORDER_NOT_FOUND','No encontramos una orden propia con ese ID.',404);
  if(order.data.status!=='AWAITING_PAYMENT')throw apiError_('ORDER_STATE_INVALID','La orden no acepta un nuevo pago.',409);
  var network=cleanString_(input.network,20).toUpperCase(); assert_(['TRC20','ERC20'].indexOf(network)>=0,'NETWORK_INVALID','Selecciona TRC20 o ERC20.');
  var idem=cleanString_(input.idempotencyKey,120);assert_(idem.length>=12,'IDEMPOTENCY_REQUIRED','Esta operación requiere una clave de idempotencia.');
  var existing=findRecord_('Payments','idempotencyKey',context.user.id+':'+idem);if(existing)return sanitizePayment_(existing.data);
  var provider=getCryptoPaymentProvider_(network); // Fails closed until a real adapter is registered.
  var request=provider.createPaymentRequest({orderId:order.data.id,amount:Number(order.data.subtotal),currency:order.data.currency,network:network,expiresInMinutes:Number(getSetting_('PAYMENT_EXPIRATION_MINUTES',30))});
  var now=nowIso_();var payment={id:newId_('pay'),orderId:order.data.id,provider:provider.name,providerPaymentId:request.id,network:network,tokenContract:request.tokenContract,destinationAddress:validateNetworkAddress_(network,request.address),expectedAmount:Number(order.data.subtotal),currency:order.data.currency,transactionHash:'',confirmations:0,status:'PENDING',expiresAt:request.expiresAt,confirmedAt:'',idempotencyKey:context.user.id+':'+idem,createdAt:now,updatedAt:now,schemaVersion:1};insertRecord_('Payments',payment);updateRecord_('Orders',order.rowNumber,{network:network,updatedAt:now});return sanitizePayment_(payment);
}

function verifyPayment_(context,input){
  var found=findRecord_('Payments','id',cleanString_(input.paymentId,100));if(!found)throw apiError_('PAYMENT_NOT_FOUND','No encontramos el pago.',404);var order=findRecord_('Orders','id',found.data.orderId);if(!order||order.data.buyerId!==context.user.id)throw apiError_('PAYMENT_NOT_FOUND','No encontramos un pago propio con ese ID.',404);
  if(found.data.status==='CONFIRMED')return sanitizePayment_(found.data);if(new Date(found.data.expiresAt)<new Date()){updateRecord_('Payments',found.rowNumber,{status:'EXPIRED',updatedAt:nowIso_()});throw apiError_('PAYMENT_EXPIRED','La solicitud de pago expiró.',409);}
  var provider=getCryptoPaymentProvider_(found.data.network);var verification=provider.verifyPayment(found.data.providerPaymentId);return finalizeVerifiedPayment_(found,order,verification);
}

function finalizeVerifiedPayment_(paymentFound,orderFound,verification){
  validateVerifiedTransfer_(paymentFound.data,verification);var lock=LockService.getScriptLock();lock.waitLock(30000);try{var current=findRecord_('Payments','id',paymentFound.data.id);if(current.data.status==='CONFIRMED')return sanitizePayment_(current.data);var now=nowIso_();var payment=updateRecord_('Payments',current.rowNumber,{transactionHash:verification.transactionHash,confirmations:verification.confirmations,status:'CONFIRMED',confirmedAt:now,updatedAt:now});updateRecord_('Orders',orderFound.rowNumber,{status:'COMPLETED',updatedAt:now});grantOrderAccess_(orderFound.data);settleCommission_(orderFound.data);insertRecord_('Transactions',{id:newId_('txn'),userId:orderFound.data.buyerId,type:'PURCHASE',referenceType:'Order',referenceId:orderFound.data.id,amount:-Number(orderFound.data.subtotal),currency:orderFound.data.currency,network:paymentFound.data.network,transactionHash:verification.transactionHash,status:'CONFIRMED',createdAt:now,schemaVersion:1});return sanitizePayment_(payment);}finally{lock.releaseLock();}
}
function sanitizePayment_(p){return{id:p.id,orderId:p.orderId,network:p.network,token:'USDT',destinationAddress:p.destinationAddress,expectedAmount:Number(p.expectedAmount),currency:p.currency,transactionHash:p.transactionHash,status:p.status,expiresAt:p.expiresAt,confirmedAt:p.confirmedAt};}

function handlePaymentWebhook_(input){
  var providerName=cleanString_(input.provider,80);var eventId=cleanString_(input.eventId,150);assert_(providerName&&eventId,'WEBHOOK_INVALID','El webhook no incluye sus identificadores.');
  if(findRecord_('WebhookEvents','eventId',providerName+':'+eventId))return{received:true,duplicate:true};
  throw apiError_('WEBHOOK_PROVIDER_NOT_CONFIGURED','No existe un verificador de firma instalado para este proveedor.',503);
}

// =============================================================================
// MODULE: Wallet
// =============================================================================

function getWallet_(context){var found=findRecord_('Wallets','userId',context.user.id);if(!found)throw apiError_('WALLET_NOT_FOUND','No encontramos tu wallet.',404);return{id:found.data.id,available:Number(found.data.availableBalance),pending:Number(found.data.pendingBalance),totalEarned:Number(found.data.totalEarned),totalSpent:Number(found.data.totalSpent),currency:found.data.currency,transactions:listRecords_('Transactions').filter(function(t){return t.userId===context.user.id;}).slice(-100).reverse()};}
function settleCommission_(order){var commission=findRecord_('Commissions','orderId',order.id);if(!commission||commission.data.status==='SETTLED')return;var wallet=findRecord_('Wallets','userId',order.sellerId);if(!wallet)throw new Error('Seller wallet missing');updateRecord_('Wallets',wallet.rowNumber,{availableBalance:roundMoney_(Number(wallet.data.availableBalance)+Number(commission.data.sellerAmount)),totalEarned:roundMoney_(Number(wallet.data.totalEarned)+Number(commission.data.sellerAmount)),updatedAt:nowIso_()});updateRecord_('Commissions',commission.rowNumber,{status:'SETTLED'});}

// =============================================================================
// MODULE: Withdrawals
// =============================================================================

function createWithdrawal_(context,input){var network=cleanString_(input.network,20).toUpperCase();var address=validateNetworkAddress_(network,input.address);var amount=Number(input.amount);var minimum=Number(getSetting_('MINIMUM_WITHDRAWAL',10));assert_(amount>=minimum,'AMOUNT_TOO_LOW','El retiro no alcanza el mínimo configurado.');var wallet=findRecord_('Wallets','userId',context.user.id);if(!wallet||Number(wallet.data.availableBalance)<amount)throw apiError_('INSUFFICIENT_BALANCE','El balance disponible no cubre este retiro.',409);var fee=Number(getSetting_('WITHDRAWAL_FEE_'+network,0));var now=nowIso_();return insertRecord_('Withdrawals',{id:newId_('wdr'),userId:context.user.id,network:network,address:address,amount:amount,fee:fee,netAmount:roundMoney_(amount-fee),currency:'USDT',transactionHash:'',status:'REQUESTED',createdAt:now,updatedAt:now,schemaVersion:1});}

// =============================================================================
// MODULE: Meetings
// =============================================================================

function findMeetingByInput_(input){
  if(input.meetingId)return findRecord_('Meetings','id',cleanString_(input.meetingId,100));
  var code=cleanString_(input.roomCode,100).toUpperCase();
  return code?findRecord_('Meetings','roomCodeHash',sha256_(code)):null;
}

function requireMeetingMember_(context,meeting){
  if(!meeting)throw apiError_('MEETING_NOT_FOUND','La sala no existe o ya terminó.',404);
  var participant=listRecords_('MeetingParticipants').filter(function(item){return item.meetingId===meeting.data.id&&item.userId===context.user.id&&item.status!=='DENIED';})[0];
  if(context.user.id!==meeting.data.hostId&&!participant)throw apiError_('FORBIDDEN','No perteneces a esta reunión.',403);
  return participant||{role:'HOST',status:'ADMITTED'};
}

function requireMeetingHost_(context,meeting){
  if(!meeting||meeting.data.hostId!==context.user.id)throw apiError_('FORBIDDEN','Solo el anfitrión puede realizar esta acción.',403);
  return meeting;
}

function meetingSummary_(meeting,context){
  return{id:meeting.id,title:meeting.title,roomCode:meeting.roomCode||'',status:meeting.status,waitingRoom:String(meeting.waitingRoom)==='true'||meeting.waitingRoom===true,locked:String(meeting.locked)==='true'||meeting.locked===true,host:meeting.hostId===context.user.id,hostId:meeting.hostId,startsAt:meeting.startsAt,endedAt:meeting.endedAt||''};
}

function uniqueRoomCode_(){
  for(var attempt=0;attempt<8;attempt++){var raw=randomToken_().replace(/[^A-Za-z0-9]/g,'').slice(0,8).toUpperCase();var code=raw.slice(0,4)+'-'+raw.slice(4,8);if(!findRecord_('Meetings','roomCodeHash',sha256_(code)))return code;}
  throw apiError_('ROOM_CODE_UNAVAILABLE','No fue posible generar un código de reunión.',503);
}

function createMeeting_(context,input){
  if(!getBooleanSetting_('MEETINGS_ENABLED',true))throw apiError_('MEETINGS_DISABLED','Las reuniones están temporalmente desactivadas.',503);
  var rawCode=uniqueRoomCode_();var rawPassword=cleanString_(input.password,100);var salt=randomToken_();var now=nowIso_();
  var meeting={id:newId_('mtg'),hostId:context.user.id,roomCode:rawCode,roomCodeHash:sha256_(rawCode),passwordHash:rawPassword?hashPassword_(rawPassword,salt)+':'+salt:'',title:cleanString_(input.title,140)||'Reunión de '+context.user.name,waitingRoom:input.waitingRoom!==false,locked:false,permissionsJson:JSON.stringify({screenShare:'ALL',chat:true,reactions:true,hostCanMute:true}),status:'ACTIVE',startsAt:now,endedAt:'',createdAt:now,updatedAt:now,schemaVersion:1};
  insertRecord_('Meetings',meeting);insertRecord_('MeetingParticipants',{id:newId_('mtp'),meetingId:meeting.id,userId:context.user.id,role:'HOST',status:'ADMITTED',joinedAt:now,leftAt:'',permissionsJson:'{}',schemaVersion:1});
  logSecurityEvent_(context.user.id,'MEETING_CREATED','INFO','Meeting',meeting.id,{});
  return meetingSummary_(meeting,context);
}

function joinMeeting_(context,input){
  var meeting=findMeetingByInput_(input);if(!meeting||meeting.data.status==='ENDED')throw apiError_('MEETING_NOT_FOUND','La sala no existe o ya terminó.',404);
  var isHost=context.user.id===meeting.data.hostId;
  if(!isHost&&(meeting.data.locked===true||String(meeting.data.locked)==='true'))throw apiError_('MEETING_LOCKED','La sala está bloqueada por el anfitrión.',403);
  if(meeting.data.passwordHash&&!isHost){var parts=String(meeting.data.passwordHash).split(':');var salt=parts.pop();var expected=parts.join(':');if(!constantTimeEqual_(hashPassword_(String(input.password||''),salt),expected))throw apiError_('MEETING_PASSWORD_INVALID','La contraseña de la sala no coincide.',401);}
  var participants=listRecords_('MeetingParticipants');var participant=participants.filter(function(p){return p.meetingId===meeting.data.id&&p.userId===context.user.id;})[0];
  var waiting=meeting.data.waitingRoom===true||String(meeting.data.waitingRoom)==='true';var previousStatus=participant?participant.status:'';var status=isHost?'ADMITTED':(previousStatus==='INVITED'?(waiting?'WAITING':'ADMITTED'):(participant?previousStatus:(waiting?'WAITING':'ADMITTED')));var role=isHost?'HOST':'PARTICIPANT';
  if(status==='DENIED')throw apiError_('MEETING_DENIED','El anfitrión no autorizó tu ingreso.',403);
  if(!participant)insertRecord_('MeetingParticipants',{id:newId_('mtp'),meetingId:meeting.data.id,userId:context.user.id,role:role,status:status,joinedAt:status==='ADMITTED'?nowIso_():'',leftAt:'',permissionsJson:'{}',schemaVersion:1});
  else if(status!==previousStatus||(status==='ADMITTED'&&!participant.joinedAt)){var found=findRecord_('MeetingParticipants','id',participant.id);if(found)updateRecord_('MeetingParticipants',found.rowNumber,{status:status,joinedAt:status==='ADMITTED'?nowIso_():participant.joinedAt,leftAt:''});}
  var signaling=PropertiesService.getScriptProperties().getProperty('SIGNALING_URL');
  return{meetingId:meeting.data.id,title:meeting.data.title,roomCode:meeting.data.roomCode||cleanString_(input.roomCode,100).toUpperCase(),hostId:meeting.data.hostId,role:role,status:status,waitingRoom:waiting,locked:String(meeting.data.locked)==='true'||meeting.data.locked===true,signalingConfigured:!!signaling,signalingUrl:signaling||null,meetingToken:status==='ADMITTED'?createMeetingToken_(meeting.data.id,context.user.id,context.user.name,status,role):null,iceServers:getMeetingIceServers_(),messages:status==='ADMITTED'?getMeetingMessages_(context,{meetingId:meeting.data.id,limit:100}):[]};
}

function getMyMeetings_(context){
  var memberships={};listRecords_('MeetingParticipants').forEach(function(item){if(item.userId===context.user.id&&item.status!=='DENIED')memberships[item.meetingId]=true;});
  return listRecords_('Meetings').filter(function(item){return item.hostId===context.user.id||memberships[item.id];}).slice(-40).reverse().map(function(item){return meetingSummary_(item,context);});
}

function getMeetingState_(context,input){
  var meeting=findMeetingByInput_(input);var member=requireMeetingMember_(context,meeting);var result=meetingSummary_(meeting.data,context);result.role=meeting.data.hostId===context.user.id?'HOST':member.role;result.participantStatus=member.status;result.messages=member.status==='ADMITTED'?getMeetingMessages_(context,{meetingId:meeting.data.id,limit:100}):[];
  if(result.host){var users={};listRecords_('Users').forEach(function(item){users[item.id]=item;});result.waitingParticipants=listRecords_('MeetingParticipants').filter(function(item){return item.meetingId===meeting.data.id&&item.status==='WAITING';}).map(function(item){var user=users[item.userId]||{};return{id:item.id,userId:item.userId,name:user.name||'Usuario',username:user.username||'',avatar:user.avatar||''};});}
  return result;
}

function updateParticipantAdmission_(context,input,status){
  var meeting=findMeetingByInput_(input);requireMeetingHost_(context,meeting);assert_(['ADMITTED','DENIED'].indexOf(status)>=0,'INVALID_STATUS','Estado de admisión inválido.');
  var found=findRecord_('MeetingParticipants','id',cleanString_(input.participantId,100));if(!found||found.data.meetingId!==meeting.data.id)throw apiError_('PARTICIPANT_NOT_FOUND','No encontramos a ese participante.',404);
  updateRecord_('MeetingParticipants',found.rowNumber,{status:status,joinedAt:status==='ADMITTED'?nowIso_():'',leftAt:status==='DENIED'?nowIso_():''});
  createNotification_(found.data.userId,'MEETING_'+status,status==='ADMITTED'?'Ingreso autorizado':'Ingreso rechazado',meeting.data.title,'Meeting',meeting.data.id);
  return{participantId:found.data.id,status:status};
}

function setMeetingLocked_(context,input){var meeting=findMeetingByInput_(input);requireMeetingHost_(context,meeting);var locked=Boolean(input.locked);updateRecord_('Meetings',meeting.rowNumber,{locked:locked,updatedAt:nowIso_()});return{locked:locked};}

function endMeeting_(context,input){
  var meeting=findMeetingByInput_(input);requireMeetingHost_(context,meeting);if(meeting.data.status!=='ENDED')updateRecord_('Meetings',meeting.rowNumber,{status:'ENDED',endedAt:nowIso_(),updatedAt:nowIso_()});
  logSecurityEvent_(context.user.id,'MEETING_ENDED','INFO','Meeting',meeting.data.id,{});return{meetingId:meeting.data.id,status:'ENDED'};
}

function listCommunityMembers_(context,input){var query=cleanString_(input.query,80).toLowerCase();return listRecords_('Users').filter(function(item){return item.id!==context.user.id&&item.status==='ACTIVE'&&(!query||(String(item.name)+' '+String(item.username)).toLowerCase().indexOf(query)>=0);}).slice(0,100).map(function(item){return{id:item.id,name:item.name,username:item.username,avatar:item.avatar||''};});}

function inviteToMeeting_(context,input){
  var meeting=findMeetingByInput_(input);requireMeetingHost_(context,meeting);var invitee=findRecord_('Users','id',cleanString_(input.userId,100));if(!invitee||invitee.data.status!=='ACTIVE')throw apiError_('USER_NOT_FOUND','No encontramos a ese usuario activo.',404);if(invitee.data.id===context.user.id)throw apiError_('INVALID_INVITEE','Ya eres el anfitrión de la reunión.',400);
  var existing=listRecords_('MeetingInvitations').filter(function(item){return item.meetingId===meeting.data.id&&item.inviteeId===invitee.data.id;})[0];var invitation;
  if(existing){var found=findRecord_('MeetingInvitations','id',existing.id);invitation=updateRecord_('MeetingInvitations',found.rowNumber,{status:'PENDING',createdAt:nowIso_(),respondedAt:''});}
  else invitation=insertRecord_('MeetingInvitations',{id:newId_('mti'),meetingId:meeting.data.id,inviterId:context.user.id,inviteeId:invitee.data.id,status:'PENDING',createdAt:nowIso_(),respondedAt:'',schemaVersion:1});
  var participant=listRecords_('MeetingParticipants').filter(function(item){return item.meetingId===meeting.data.id&&item.userId===invitee.data.id;})[0];if(!participant)insertRecord_('MeetingParticipants',{id:newId_('mtp'),meetingId:meeting.data.id,userId:invitee.data.id,role:'PARTICIPANT',status:'INVITED',joinedAt:'',leftAt:'',permissionsJson:'{}',schemaVersion:1});
  createNotification_(invitee.data.id,'MEETING_INVITE',context.user.name+' te invitó a una reunión',meeting.data.title+' · '+meeting.data.roomCode,'Meeting',meeting.data.id);
  return{id:invitation.id,userId:invitee.data.id,name:invitee.data.name,status:'PENDING'};
}

function meetingMessageView_(message,users,reactions,viewerId){
  var grouped={};reactions.filter(function(item){return item.messageId===message.id&&String(item.active)!=='false';}).forEach(function(item){if(!grouped[item.emoji])grouped[item.emoji]={emoji:item.emoji,count:0,mine:false};grouped[item.emoji].count++;if(item.userId===viewerId)grouped[item.emoji].mine=true;});var sender=users[message.senderId]||{};
  return{id:message.id,meetingId:message.meetingId,senderId:message.senderId,senderName:sender.name||'Usuario',senderUsername:sender.username||'',body:message.deletedAt?'Mensaje eliminado':message.body,replyToId:message.replyToId||'',createdAt:message.createdAt,reactions:Object.keys(grouped).map(function(key){return grouped[key];})};
}

function getMeetingMessages_(context,input){
  var meeting=findMeetingByInput_(input);var member=requireMeetingMember_(context,meeting);if(member.status!=='ADMITTED')return[];var limit=Math.max(1,Math.min(100,Number(input.limit)||100));var users={};listRecords_('Users').forEach(function(item){users[item.id]=item;});var reactions=listRecords_('MeetingMessageReactions');return listRecords_('MeetingMessages').filter(function(item){return item.meetingId===meeting.data.id;}).slice(-limit).map(function(item){return meetingMessageView_(item,users,reactions,context.user.id);});
}

function postMeetingMessage_(context,input){
  var meeting=findMeetingByInput_(input);var member=requireMeetingMember_(context,meeting);if(meeting.data.status==='ENDED')throw apiError_('MEETING_ENDED','La reunión ya terminó.',409);if(member.status!=='ADMITTED')throw apiError_('MEETING_WAITING','Aún no has sido admitido.',403);var body=cleanString_(input.body,2000);assert_(body.length>0,'EMPTY_MESSAGE','Escribe un mensaje.');var replyToId=cleanString_(input.replyToId,100);if(replyToId){var reply=findRecord_('MeetingMessages','id',replyToId);if(!reply||reply.data.meetingId!==meeting.data.id)throw apiError_('INVALID_REPLY','El mensaje respondido no pertenece a esta reunión.',400);}
  var message=insertRecord_('MeetingMessages',{id:newId_('msg'),meetingId:meeting.data.id,senderId:context.user.id,body:body,replyToId:replyToId,createdAt:nowIso_(),editedAt:'',deletedAt:'',schemaVersion:1});var users={};users[context.user.id]=context.user;return meetingMessageView_(message,users,[],context.user.id);
}

function reactToMeetingMessage_(context,input){
  var meeting=findMeetingByInput_(input);var member=requireMeetingMember_(context,meeting);if(member.status!=='ADMITTED')throw apiError_('MEETING_WAITING','Aún no has sido admitido.',403);var emoji=cleanString_(input.emoji,8);assert_(['👍','👏','❤️','😂','🎉','🔥'].indexOf(emoji)>=0,'INVALID_REACTION','Reacción no permitida.');var message=findRecord_('MeetingMessages','id',cleanString_(input.messageId,100));if(!message||message.data.meetingId!==meeting.data.id)throw apiError_('MESSAGE_NOT_FOUND','No encontramos ese mensaje.',404);var existing=listRecords_('MeetingMessageReactions').filter(function(item){return item.messageId===message.data.id&&item.userId===context.user.id&&item.emoji===emoji;})[0];var active=true;
  if(existing){active=String(existing.active)==='false';var found=findRecord_('MeetingMessageReactions','id',existing.id);updateRecord_('MeetingMessageReactions',found.rowNumber,{active:active,updatedAt:nowIso_()});}else insertRecord_('MeetingMessageReactions',{id:newId_('mmr'),meetingId:meeting.data.id,messageId:message.data.id,userId:context.user.id,emoji:emoji,active:true,createdAt:nowIso_(),updatedAt:nowIso_(),schemaVersion:1});
  return{messageId:message.data.id,emoji:emoji,active:active,userId:context.user.id};
}

function meetingRealtimeKey_(meetingId,suffix){return'mrt:'+sha256_(meetingId).slice(0,20)+':'+suffix;}
function parseCachedJson_(value,fallback){try{return value?JSON.parse(value):fallback;}catch(ignore){return fallback;}}

function pollMeetingRealtime_(context,input){
  var meeting=findMeetingByInput_(input);var member=requireMeetingMember_(context,meeting);if(member.status!=='ADMITTED')throw apiError_('MEETING_WAITING','Aún no has sido admitido.',403);
  var connectionId=cleanString_(input.connectionId,100);assert_(/^[A-Za-z0-9_-]{8,100}$/.test(connectionId),'INVALID_CONNECTION','Identificador de conexión inválido.');var now=Date.now();var cache=CacheService.getScriptCache();var lock=LockService.getScriptLock();var presenceKey=meetingRealtimeKey_(meeting.data.id,'presence');var mailboxKey=meetingRealtimeKey_(meeting.data.id,'box:'+connectionId);var presence;
  lock.waitLock(5000);try{presence=parseCachedJson_(cache.get(presenceKey),{});Object.keys(presence).forEach(function(key){if(now-Number(presence[key].lastSeen||0)>20000)delete presence[key];});var state=input.presence||{};presence[connectionId]={peerId:connectionId,userId:context.user.id,name:context.user.name,role:meeting.data.hostId===context.user.id?'HOST':'PARTICIPANT',mic:Boolean(state.mic),camera:Boolean(state.camera),sharing:Boolean(state.sharing),handRaised:Boolean(state.handRaised),speaking:Boolean(state.mic)&&Boolean(state.speaking),lastSeen:now};cache.put(presenceKey,JSON.stringify(presence),30);}finally{lock.releaseLock();}
  var signals=parseCachedJson_(cache.get(mailboxKey),[]);if(signals.length)cache.remove(mailboxKey);var peers=Object.keys(presence).filter(function(key){return key!==connectionId;}).map(function(key){return presence[key];});var messages=[];if(input.includeMessages===true||String(input.includeMessages)==='true')messages=getMeetingMessages_(context,{meetingId:meeting.data.id,limit:100});
  return{meetingId:meeting.data.id,status:meeting.data.status,peers:peers,signals:signals.slice(-80),messages:messages,serverTime:nowIso_()};
}

function postMeetingSignals_(context,input){
  var meeting=findMeetingByInput_(input);var member=requireMeetingMember_(context,meeting);if(member.status!=='ADMITTED')throw apiError_('MEETING_WAITING','Aún no has sido admitido.',403);var senderId=cleanString_(input.connectionId,100);var signals=Array.isArray(input.signals)?input.signals.slice(0,30):[];var cache=CacheService.getScriptCache();var presence=parseCachedJson_(cache.get(meetingRealtimeKey_(meeting.data.id,'presence')),{});var isHost=meeting.data.hostId===context.user.id;var lock=LockService.getScriptLock();var delivered=0;
  lock.waitLock(5000);try{signals.forEach(function(signal){var type=cleanString_(signal.type,30);if(['offer','answer','ice','reaction','force-mute'].indexOf(type)<0)return;if(type==='force-mute'&&!isHost)return;var targets=[];if(type==='reaction')targets=Object.keys(presence).filter(function(key){return key!==senderId;});else{var target=cleanString_(signal.target,100);if(target&&presence[target])targets=[target];}targets.forEach(function(targetId){var key=meetingRealtimeKey_(meeting.data.id,'box:'+targetId);var mailbox=parseCachedJson_(cache.get(key),[]);var data=signal.data;if(JSON.stringify(data||null).length>30000)return;mailbox.push({id:newId_('sig'),type:type,source:senderId,data:data||null,emoji:cleanString_(signal.emoji,8),by:context.user.name,createdAt:nowIso_()});cache.put(key,JSON.stringify(mailbox.slice(-80)),120);delivered++;});});}finally{lock.releaseLock();}
  return{delivered:delivered};
}

function leaveMeetingRealtime_(context,input){var meeting=findMeetingByInput_(input);requireMeetingMember_(context,meeting);var connectionId=cleanString_(input.connectionId,100);var cache=CacheService.getScriptCache();var key=meetingRealtimeKey_(meeting.data.id,'presence');var lock=LockService.getScriptLock();lock.waitLock(5000);try{var presence=parseCachedJson_(cache.get(key),{});delete presence[connectionId];cache.put(key,JSON.stringify(presence),30);cache.remove(meetingRealtimeKey_(meeting.data.id,'box:'+connectionId));}finally{lock.releaseLock();}return{left:true};}

function createMeetingToken_(meetingId,userId,name,status,role){var expiresAt=Date.now()+60*60*1000;var nonce=randomToken_();var secret=PropertiesService.getScriptProperties().getProperty('MEETING_TOKEN_SECRET');if(!secret)return null;var payload=Utilities.base64EncodeWebSafe(JSON.stringify({meetingId:meetingId,userId:userId,name:name,status:status,role:role||'PARTICIPANT',expiresAt:expiresAt,nonce:nonce})).replace(/=+$/,'');var signature=Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(payload,secret)).replace(/=+$/,'');return payload+'.'+signature;}

function getMeetingIceServers_(){var raw=PropertiesService.getScriptProperties().getProperty('ICE_SERVERS_JSON');if(!raw)return[];try{var parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed.slice(0,5).map(function(item){return{urls:item.urls,username:item.username||'',credential:item.credential||''};}):[];}catch(error){console.error('Invalid ICE_SERVERS_JSON');return[];}}

// =============================================================================
// MODULE: Streams
// =============================================================================

function createStream_(context,input){
  if(!getBooleanSetting_('STREAMING_ENABLED',false))throw apiError_('STREAMING_NOT_CONFIGURED','El streaming requiere configurar señalización, TURN y un SFU.',503);
  if(['CREATOR','ADMIN'].indexOf(context.user.role)<0)throw apiError_('FORBIDDEN','Tu rol no puede iniciar transmisiones.',403);
  var transport=PropertiesService.getScriptProperties().getProperty('STREAMING_PROVIDER');if(!transport)throw apiError_('STREAMING_NOT_CONFIGURED','Configura un proveedor de transporte antes de iniciar.',503);
  return insertRecord_('Streams',{id:newId_('str'),hostId:context.user.id,title:cleanString_(input.title,140),description:cleanString_(input.description,1000),thumbnail:cleanString_(input.thumbnail,1000),categoryId:cleanString_(input.categoryId,100),status:'CREATED',startedAt:'',endedAt:'',viewerCount:0,createdAt:nowIso_(),schemaVersion:1});
}

// =============================================================================
// MODULE: Notifications
// =============================================================================

function createNotification_(userId,type,title,body,resourceType,resourceId){return insertRecord_('Notifications',{id:newId_('not'),userId:userId,type:type,title:cleanString_(title,140),body:cleanString_(body,1000),resourceType:resourceType||'',resourceId:resourceId||'',readAt:'',createdAt:nowIso_(),schemaVersion:1});}
function getNotifications_(context){return listRecords_('Notifications').filter(function(n){return n.userId===context.user.id;}).slice(-100).reverse();}

// =============================================================================
// MODULE: Admin
// =============================================================================

function updateSetting_(context,key,value){requireAdmin_(context);var allowed=['APP_NAME','REGISTRATION_ENABLED','MARKETPLACE_ENABLED','MEETINGS_ENABLED','STREAMING_ENABLED','MAINTENANCE_MODE','COMMISSION_RATE','PAYMENT_EXPIRATION_MINUTES','TRC20_ENABLED','ERC20_ENABLED','MINIMUM_WITHDRAWAL'];if(allowed.indexOf(key)<0)throw apiError_('SETTING_NOT_ALLOWED','Esta opción no puede modificarse desde el panel.',403);var found=findRecord_('Settings','key',key);if(!found)throw apiError_('SETTING_NOT_FOUND','No encontramos esta opción.',404);var updated=updateRecord_('Settings',found.rowNumber,{value:String(value),updatedBy:context.user.id,updatedAt:nowIso_()});CacheService.getScriptCache().remove('settings:all');logSecurityEvent_(context.user.id,'SETTING_CHANGED','WARNING','Setting',key,{value:String(value)});return updated;}
function exportDatabase_(){var context=arguments[0];requireAdmin_(context);return{spreadsheetId:getDatabase_().getId(),exportedAt:nowIso_(),sheets:Object.keys(SHEET_SCHEMAS)};}

// =============================================================================
// MODULE: Bootstrap
// =============================================================================

function getBootstrapData_(context,input){
  var requested=input.modules;if(typeof requested==='string')requested=requested.split(',');if(!Array.isArray(requested)||!requested.length)requested=['user'];
  var allowed={user:true,config:true,profile:true,wallet:true,notifications:true,orders:true,products:true,meetings:true};var modules=[];requested.forEach(function(name){name=cleanString_(name,30);if(allowed[name]&&modules.indexOf(name)<0)modules.push(name);});
  var result={generatedAt:nowIso_()};
  if(modules.indexOf('user')>=0)result.user=sanitizeUser_(context.user);
  if(modules.indexOf('config')>=0)result.config=getPublicConfig_();
  if(modules.indexOf('profile')>=0){var profile=findRecord_('Profiles','userId',context.user.id);result.profile=profile?profile.data:null;}
  if(modules.indexOf('wallet')>=0){var wallet=findRecord_('Wallets','userId',context.user.id);result.wallet=wallet?{id:wallet.data.id,available:Number(wallet.data.availableBalance),pending:Number(wallet.data.pendingBalance),totalEarned:Number(wallet.data.totalEarned),totalSpent:Number(wallet.data.totalSpent),currency:wallet.data.currency}:null;}
  if(modules.indexOf('notifications')>=0)result.notifications=listRecords_('Notifications').filter(function(item){return item.userId===context.user.id&&!item.readAt;}).slice(-20).reverse();
  if(modules.indexOf('orders')>=0)result.orders=getOrders_(context);
  if(modules.indexOf('products')>=0)result.products=listProducts_(input);
  if(modules.indexOf('meetings')>=0){var participantMeetingIds={};listRecords_('MeetingParticipants').forEach(function(item){if(item.userId===context.user.id&&item.status!=='DENIED')participantMeetingIds[item.meetingId]=true;});result.meetings=listRecords_('Meetings').filter(function(item){return item.hostId===context.user.id||participantMeetingIds[item.id];}).slice(-20).reverse().map(function(item){return{id:item.id,title:item.title,roomCode:item.roomCode||'',status:item.status,startsAt:item.startsAt,host:item.hostId===context.user.id,waitingRoom:String(item.waitingRoom)==='true'||item.waitingRoom===true};});}
  return result;
}

// =============================================================================
// MODULE: Code
// =============================================================================

function doGet(e) {
  return routeRequest_('GET', e);
}

function doPost(e) {
  return routeRequest_('POST', e);
}

function routeRequest_(method, e) {
  var requestId = newId_('req');
  var started = Date.now();
  var action = 'unknown';
  beginRequest_();
  try {
    ensureApplicationReady_();
    var body = parseBody_(e);
    action = String((e && e.parameter && e.parameter.action) || body.action || 'health');
    enforceRateLimit_(action, body);
    var handlers = {
      health: function() { return getHealth_(); },
      config: function() { return getPublicConfig_(); },
      register: function() { requireMethod_(method, 'POST'); return registerUser_(body); },
      login: function() { requireMethod_(method, 'POST'); return loginUser_(body); },
      logout: function() { requireMethod_(method, 'POST'); return logoutUser_(requireSession_(body)); },
      me: function() { return sanitizeUser_(requireSession_(body).user); },
      getBootstrapData: function() { return getBootstrapData_(requireSession_(body), body); },
      getProducts: function() { return listProducts_(body); },
      getProduct: function() { return getProduct_(body.id); },
      createOrder: function() { requireMethod_(method, 'POST'); return createOrder_(requireSession_(body), body); },
      createPayment: function() { requireMethod_(method, 'POST'); return createPayment_(requireSession_(body), body); },
      verifyPayment: function() { requireMethod_(method, 'POST'); return verifyPayment_(requireSession_(body), body); },
      paymentWebhook: function() { requireMethod_(method, 'POST'); return handlePaymentWebhook_(body); },
      getOrders: function() { return getOrders_(requireSession_(body)); },
      getWallet: function() { return getWallet_(requireSession_(body)); },
      createMeeting: function() { requireMethod_(method, 'POST'); return createMeeting_(requireSession_(body), body); },
      joinMeeting: function() { requireMethod_(method, 'POST'); return joinMeeting_(requireSession_(body), body); },
      getMyMeetings: function() { return getMyMeetings_(requireSession_(body)); },
      getMeetingState: function() { return getMeetingState_(requireSession_(body), body); },
      admitMeetingParticipant: function() { requireMethod_(method, 'POST'); return updateParticipantAdmission_(requireSession_(body), body, 'ADMITTED'); },
      denyMeetingParticipant: function() { requireMethod_(method, 'POST'); return updateParticipantAdmission_(requireSession_(body), body, 'DENIED'); },
      setMeetingLocked: function() { requireMethod_(method, 'POST'); return setMeetingLocked_(requireSession_(body), body); },
      endMeeting: function() { requireMethod_(method, 'POST'); return endMeeting_(requireSession_(body), body); },
      getCommunityMembers: function() { return listCommunityMembers_(requireSession_(body), body); },
      inviteToMeeting: function() { requireMethod_(method, 'POST'); return inviteToMeeting_(requireSession_(body), body); },
      getMeetingMessages: function() { return getMeetingMessages_(requireSession_(body), body); },
      postMeetingMessage: function() { requireMethod_(method, 'POST'); return postMeetingMessage_(requireSession_(body), body); },
      reactToMeetingMessage: function() { requireMethod_(method, 'POST'); return reactToMeetingMessage_(requireSession_(body), body); },
      pollMeetingRealtime: function() { requireMethod_(method, 'POST'); return pollMeetingRealtime_(requireSession_(body), body); },
      postMeetingSignals: function() { requireMethod_(method, 'POST'); return postMeetingSignals_(requireSession_(body), body); },
      leaveMeetingRealtime: function() { requireMethod_(method, 'POST'); return leaveMeetingRealtime_(requireSession_(body), body); },
      initializeDatabase: function() { requireAdmin_(requireSession_(body)); return initializeDatabase(); }
    };
    if (!handlers[action]) throw apiError_('NOT_FOUND', 'La acción solicitada no existe.', 404);
    var data = handlers[action]();
    var response = jsonResponse_({ ok:true, data:data, requestId:requestId });
    observeRequest_(action, Date.now() - started, true);
    return response;
  } catch (error) {
    var failure = jsonResponse_({ ok:false, error:{ code:error.code || 'INTERNAL_ERROR', message:error.publicMessage || 'No fue posible completar la solicitud.' }, requestId:requestId });
    observeRequest_(action, Date.now() - started, false);
    return failure;
  }
}

function parseBody_(e) {
  var body = {};
  if (e && e.postData && e.postData.contents) {
    try { body = JSON.parse(e.postData.contents); }
    catch (ignore) { throw apiError_('INVALID_JSON', 'El cuerpo de la solicitud no es JSON válido.', 400); }
  }
  if (e && e.parameter) Object.keys(e.parameter).forEach(function(key) { if (body[key] === undefined) body[key] = e.parameter[key]; });
  return body;
}

function jsonResponse_(payload) {
  var serialized = JSON.stringify(payload);
  if (REQUEST_CONTEXT_) REQUEST_CONTEXT_.responseBytes = serialized.length;
  return ContentService.createTextOutput(serialized).setMimeType(ContentService.MimeType.JSON);
}
